sudo: required

services:
  - docker
  
env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - sudo apt-get install sshpass
  - docker pull anastop/sshd
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d
  
script:
  - sshpass -p 'root' ssh -o StrictHostKeyChecking=no root@172.18.0.10 hostname
  - sshpass -p 'root' ssh -o StrictHostKeyChecking=no root@172.18.0.11 hostname
  - sshpass -p 'root' ssh -o StrictHostKeyChecking=no root@172.18.0.12 hostname
  - ping -c 1 172.18.0.10
  - ping -c 1 172.18.0.11
  - ping -c 1 172.18.0.12

  #- ssh -o root@172.18.0.10 hostname
  #- ssh -o root@172.18.0.11 hostname
  #- ssh -o root@172.18.0.12 hostname

after_script:
  - docker-compose down
